### ISSUE TITLE
About c++modules for xmake

### ISSUE THREAD

**Issue by waruqi** [alexpanter/modules_testing#1]
Thank you very much for your example. I am making xmake (only on master branch) better support c++ modules recently. It can work very well and supports inter-module dependencies. Here are some examples.

- https://github.com/xmake-io/xmake/tree/master/tests/projects/c%2B%2B/modules
- https://github.com/xmake-io/xmake/issues/1729

Although there are still some areas that are not perfect, as I mentioned on stackoverflow, I also thought of some workaround solutions to deal with them.

- https://stackoverflow.com/questions/69564746/clangs-implicit-prebuilt-modules-is-invalid-for-the-module-implementation-unit
- https://stackoverflow.com/questions/69549286/how-to-modify-gcm-cache-path-when-using-gcc-11-to-build-c20-modules

**Comment by alexpanter** [comment]
Hi ruki,

You are very welcome! I read your stackoverflow questions with great interest. I can't speak for the gcm.cache. It seems as of now its usages are quite limited. This is unfortunate, as I would like to have the same functionality as you (apparently) can with clang `-fmodules-cache-path=` - this seems like a **much** better idea than what GCC has done with their [module mapper](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Module-Mapper.html).

Xmake looks like an interesting project. Especially if it actually does everything it promises (which is quite a lot).
I, too, have concerns with the syntax of Cmake. I might have a look at xmake at some point.

But I found that I like the approach [premake](https://github.com/premake/premake-core) is taking a lot. I prefer not to be in a different environment to run my projects (like [Bazel](https://github.com/bazelbuild/bazel) which depends on a docker environment). Instead, by directly creating a Makefile for me (or VS solution), I can inspect the build process much more easily.

But I know most of modules with gcc, currently. Right now, I'm working on a proposal for premake for [adding](https://github.com/premake/premake-core/issues/1735) modules into their C++ pipeline. At some point after that I will take a look at Clang as well.

**Comment by waruqi** [comment]
Okay, thanks for your reply.

> by directly creating a Makefile for me (or VS solution)

xmake also supports to generate makefile, VS projects, cmakelists/ninja.build
